version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb_server
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    image: doanviet027/wishy_backend:1.0.1
    container_name: wishy_server
    ports:
      - "4991:4999"
    environment:
      MONGODB_URI: mongodb://mongo:27017/magic-wishes
    env_file:
      - .env
    depends_on:
      - mongo
volumes:
  mongo_data:
